github.com:
    users:
        knightmar:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: knightmar
