github.com:
    users:
        knightmar:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: knightmar
